package it.necross.interfaces.stats.operators

enum class Operators(val identifier: String) {
    RECRUIT_SAS("Recruit SAS"),
    RECRUIT_FBI("Recruit FBI SWAT"),
    RECRUIT_GIGN("Recruit GIGN"),
    RECRUIT_SPETSNAZ("Recruit Spetsnaz"),
    RECRUIT_GSG9("Recruit GSG 9"),
    SMOKE("Smoke"),
    MUTE("Mute"),
    SLEDGE("Sledge"),
    THATCHER("Thatcher"),
    CASTLE("Castle"),
    PULSE("Pulse"),
    ASH("Ash"),
    THERMITE("Thermite"),
    DOC("Doc"),
    ROOK("Rook"),
    TWITCH("Twitch"),
    MONTAGNE("Montagne"),
    KAPKAN("Kapkan"),
    TACHANKA("Tachanka"),
    GLAZ("Glaz"),
    FUZE("Fuze"),
    JAGER("Jäger"),
    BANDIT("Bandit"),
    BLITZ("Blitz"),
    IQ("IQ"),
    FROST("Frost"),
    BUCK("Buck"),
    VALKYRIE("Valkyrie"),
    BLACKBEARD("Blackbeard"),
    CAVEIRA("Caveira"),
    CAPITAO("Capitão"),
    ECHO("Echo"),
    HIBANA("Hibana"),
    MIRA("Mira"),
    JACKEL("Jackal"),
    LESION("Lesion"),
    YING("Ying"),
    ELA("Ela"),
    ZOFIA("Zofia"),
    VIGIL("Vigil"),
    DOKKAEBI("Dokkaebi"),
    LION("Lion"),
    FINKA("Finka"),
    MAESTRO("Maestro"),
    ALIBI("Alibi"),
    CLASH("Clash"),
    MAVERICK("Maverick"),
    KAIDA("Kaid"),
    NOMAD("Nomad"),
    MOZZIE("Mozzie"),
    GRIDLOCK("Gridlock"),
    WARDEN("Warden"),
    NOKK("Nøkk"),
    GOYO("Goyo"),
    AMARU("Amaru"),
    WAMAI("Wamai"),
    KALI("Kali"),
    ORYX("Oryx"),
    IANA("Iana"),
    MELUSI("Melusi"),
    ACE("Ace"),
    ZERO("Zero"),
    ARUNI("Aruni"),
    FLORES("Flores"),
    THUNDERBIRD("Thunderbird"),
    OSA("Osa"),
}